# Generated by scripts/probe_env.py — never hand-edit. Run `make probe`.
PROBE_TIMESTAMP = "2026-09-07T22:35:03.883329+00:00"

OPEN_SPIEL_VERSION = "2.0.2"
NUM_PLAYERS = 2
NUM_DISTINCT_ACTIONS = 241
OBSERVATION_TENSOR_SIZE = 644
MAX_GAME_LENGTH = 300
MIN_UTILITY = -123.0
MAX_UTILITY = 123.0

GAME_PARAMS = {
    "gin_bonus": 25,
    "hand_size": 10,
    "knock_card": 10,
    "num_ranks": 13,
    "num_suits": 4,
    "oklahoma": False,
    "undercut_bonus": 25,
}
DRAW_UPCARD_ACTION = 52
DRAW_STOCK_ACTION = 53
PASS_ACTION = 54
KNOCK_ACTION = 55
MELD_ACTION_BASE = 56
NUM_MELD_ACTIONS = 185
WALL_STOCK_SIZE = 2

INFORMATION_STATE_TENSOR_RAISES = True
GIN_RUMMY_UTILS_METHODS = [
    "all_layoffs",
    "all_melds",
    "best_meld_group",
    "card_value",
    "int_to_meld",
    "legal_discards",
    "legal_melds",
    "meld_to_int",
    "min_deadwood",
]
RESAMPLE_FROM_INFOSTATE_WORKS = True
SIMPLE_BOT_CONSTRUCTS = True

TORCH_VERSION = "2.14.0"
MPS_BUILT = True
MPS_AVAILABLE = True

DEVICE_RECOMMENDATION = "cpu"
BENCHMARK_STANDIN = "mlp-644-512-512-256-fp32-fwd-bwd"
BENCHMARK_CPU_BATCH_256_MS_PER_ITER = 1.0751
BENCHMARK_CPU_BATCH_32_MS_PER_ITER = 0.3039
BENCHMARK_MPS_BATCH_256_MS_PER_ITER = 1.2197
BENCHMARK_MPS_BATCH_32_MS_PER_ITER = 0.5694
BENCHMARK_RAW_STEPS_PER_SEC = 70751.4
